version: "3.9"
services: 
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
    ports:
      - 80:80
    networks:
      - phpLocalNetwork
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: a3b6c9
      MYSQL_DATABASE: Hangman
    ports:
      - 3306:3306
    networks:
      - phpLocalNetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
     - 8080:80
    networks:
      - phpLocalNetwork
networks:
  phpLocalNetwork: 